##########################################################################################################################
# File automatically-generated by tool: [projectgenerator] version: [4.4.0-B60] date: [Thu Sep 05 19:41:59 CST 2024]
##########################################################################################################################

# ------------------------------------------------
# Generic Makefile (based on gcc)
#
# ChangeLog :
#	2017-02-10 - Several enhancements + project update mode
#   2015-07-22 - first version
# ------------------------------------------------

######################################
# target
######################################
TARGET = CHIP_1


######################################
# building variables
######################################
# debug build?
DEBUG = 1
# optimization
OPT = -Og


#######################################
# paths
#######################################
# Build path
BUILD_DIR = build

######################################
# source
######################################
# C sources
C_SOURCES =  \
Core/Src/main.c \
Core/Src/gpio.c \
Core/Src/freertos.c \
Core/Src/adc.c \
Core/Src/dma.c \
Core/Src/tim.c \
Core/Src/stm32f4xx_it.c \
Core/Src/stm32f4xx_hal_msp.c \
Core/Src/stm32f4xx_hal_timebase_tim.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_adc.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_adc_ex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_adc.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc_ex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ramfunc.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_gpio.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma_ex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr_ex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cortex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_exti.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim_ex.c \
Core/Src/system_stm32f4xx.c \
Middlewares/Third_Party/FreeRTOS/Source/croutine.c \
Middlewares/Third_Party/FreeRTOS/Source/event_groups.c \
Middlewares/Third_Party/FreeRTOS/Source/list.c \
Middlewares/Third_Party/FreeRTOS/Source/queue.c \
Middlewares/Third_Party/FreeRTOS/Source/stream_buffer.c \
Middlewares/Third_Party/FreeRTOS/Source/tasks.c \
Middlewares/Third_Party/FreeRTOS/Source/timers.c \
Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2/cmsis_os2.c \
Middlewares/Third_Party/FreeRTOS/Source/portable/MemMang/heap_4.c \
Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F/port.c \
Core/Src/sysmem.c \
Core/Src/syscalls.c \
BUTTON/Src/button_display.c \
BUTTON/Src/button.c \
CONTROL/Src/current_votage.c \
CONTROL/Src/current.c \
CONTROL/Src/votage.c \
DSP/Source/BasicMathFunctions/arm_abs_f32.c \
DSP/Source/BasicMathFunctions/arm_abs_q15.c \
DSP/Source/BasicMathFunctions/arm_abs_q31.c \
DSP/Source/BasicMathFunctions/arm_abs_q7.c \
DSP/Source/BasicMathFunctions/arm_add_f32.c \
DSP/Source/BasicMathFunctions/arm_add_q15.c \
DSP/Source/BasicMathFunctions/arm_add_q31.c \
DSP/Source/BasicMathFunctions/arm_add_q7.c \
DSP/Source/BasicMathFunctions/arm_dot_prod_f32.c \
DSP/Source/BasicMathFunctions/arm_dot_prod_q15.c \
DSP/Source/BasicMathFunctions/arm_dot_prod_q31.c \
DSP/Source/BasicMathFunctions/arm_dot_prod_q7.c \
DSP/Source/BasicMathFunctions/arm_mult_f32.c \
DSP/Source/BasicMathFunctions/arm_mult_q15.c \
DSP/Source/BasicMathFunctions/arm_mult_q31.c \
DSP/Source/BasicMathFunctions/arm_mult_q7.c \
DSP/Source/BasicMathFunctions/arm_negate_f32.c \
DSP/Source/BasicMathFunctions/arm_negate_q15.c \
DSP/Source/BasicMathFunctions/arm_negate_q31.c \
DSP/Source/BasicMathFunctions/arm_negate_q7.c \
DSP/Source/BasicMathFunctions/arm_offset_f32.c \
DSP/Source/BasicMathFunctions/arm_offset_q15.c \
DSP/Source/BasicMathFunctions/arm_offset_q31.c \
DSP/Source/BasicMathFunctions/arm_offset_q7.c \
DSP/Source/BasicMathFunctions/arm_scale_f32.c \
DSP/Source/BasicMathFunctions/arm_scale_q15.c \
DSP/Source/BasicMathFunctions/arm_scale_q31.c \
DSP/Source/BasicMathFunctions/arm_scale_q7.c \
DSP/Source/BasicMathFunctions/arm_shift_q15.c \
DSP/Source/BasicMathFunctions/arm_shift_q31.c \
DSP/Source/BasicMathFunctions/arm_shift_q7.c \
DSP/Source/BasicMathFunctions/arm_sub_f32.c \
DSP/Source/BasicMathFunctions/arm_sub_q15.c \
DSP/Source/BasicMathFunctions/arm_sub_q31.c \
DSP/Source/BasicMathFunctions/arm_sub_q7.c \
DSP/Source/CommonTables/arm_common_tables.c \
DSP/Source/CommonTables/arm_const_structs.c \
DSP/Source/ComplexMathFunctions/arm_cmplx_conj_f32.c \
DSP/Source/ComplexMathFunctions/arm_cmplx_conj_q15.c \
DSP/Source/ComplexMathFunctions/arm_cmplx_conj_q31.c \
DSP/Source/ComplexMathFunctions/arm_cmplx_dot_prod_f32.c \
DSP/Source/ComplexMathFunctions/arm_cmplx_dot_prod_q15.c \
DSP/Source/ComplexMathFunctions/arm_cmplx_dot_prod_q31.c \
DSP/Source/ComplexMathFunctions/arm_cmplx_mag_f32.c \
DSP/Source/ComplexMathFunctions/arm_cmplx_mag_q15.c \
DSP/Source/ComplexMathFunctions/arm_cmplx_mag_q31.c \
DSP/Source/ComplexMathFunctions/arm_cmplx_mag_squared_f32.c \
DSP/Source/ComplexMathFunctions/arm_cmplx_mag_squared_q15.c \
DSP/Source/ComplexMathFunctions/arm_cmplx_mag_squared_q31.c \
DSP/Source/ComplexMathFunctions/arm_cmplx_mult_cmplx_f32.c \
DSP/Source/ComplexMathFunctions/arm_cmplx_mult_cmplx_q15.c \
DSP/Source/ComplexMathFunctions/arm_cmplx_mult_cmplx_q31.c \
DSP/Source/ComplexMathFunctions/arm_cmplx_mult_real_f32.c \
DSP/Source/ComplexMathFunctions/arm_cmplx_mult_real_q15.c \
DSP/Source/ComplexMathFunctions/arm_cmplx_mult_real_q31.c \
DSP/Source/ControllerFunctions/arm_pid_init_f32.c \
DSP/Source/ControllerFunctions/arm_pid_init_q15.c \
DSP/Source/ControllerFunctions/arm_pid_init_q31.c \
DSP/Source/ControllerFunctions/arm_pid_reset_f32.c \
DSP/Source/ControllerFunctions/arm_pid_reset_q15.c \
DSP/Source/ControllerFunctions/arm_pid_reset_q31.c \
DSP/Source/ControllerFunctions/arm_sin_cos_f32.c \
DSP/Source/ControllerFunctions/arm_sin_cos_q31.c \
DSP/Source/FastMathFunctions/arm_cos_f32.c \
DSP/Source/FastMathFunctions/arm_cos_q15.c \
DSP/Source/FastMathFunctions/arm_cos_q31.c \
DSP/Source/FastMathFunctions/arm_sin_f32.c \
DSP/Source/FastMathFunctions/arm_sin_q15.c \
DSP/Source/FastMathFunctions/arm_sin_q31.c \
DSP/Source/FastMathFunctions/arm_sqrt_q15.c \
DSP/Source/FastMathFunctions/arm_sqrt_q31.c \
DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_init_q31.c \
DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_q31.c \
DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_f32.c \
DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q15.c \
DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q31.c \
DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f32.c \
DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q15.c \
DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q31.c \
DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q15.c \
DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q31.c \
DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f32.c \
DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f64.c \
DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f32.c \
DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f64.c \
DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f32.c \
DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f32.c \
DSP/Source/FilteringFunctions/arm_conv_f32.c \
DSP/Source/FilteringFunctions/arm_conv_fast_opt_q15.c \
DSP/Source/FilteringFunctions/arm_conv_fast_q15.c \
DSP/Source/FilteringFunctions/arm_conv_fast_q31.c \
DSP/Source/FilteringFunctions/arm_conv_opt_q15.c \
DSP/Source/FilteringFunctions/arm_conv_opt_q7.c \
DSP/Source/FilteringFunctions/arm_conv_partial_f32.c \
DSP/Source/FilteringFunctions/arm_conv_partial_fast_opt_q15.c \
DSP/Source/FilteringFunctions/arm_conv_partial_fast_q15.c \
DSP/Source/FilteringFunctions/arm_conv_partial_fast_q31.c \
DSP/Source/FilteringFunctions/arm_conv_partial_opt_q15.c \
DSP/Source/FilteringFunctions/arm_conv_partial_opt_q7.c \
DSP/Source/FilteringFunctions/arm_conv_partial_q15.c \
DSP/Source/FilteringFunctions/arm_conv_partial_q31.c \
DSP/Source/FilteringFunctions/arm_conv_partial_q7.c \
DSP/Source/FilteringFunctions/arm_conv_q15.c \
DSP/Source/FilteringFunctions/arm_conv_q31.c \
DSP/Source/FilteringFunctions/arm_conv_q7.c \
DSP/Source/FilteringFunctions/arm_correlate_f32.c \
DSP/Source/FilteringFunctions/arm_correlate_fast_opt_q15.c \
DSP/Source/FilteringFunctions/arm_correlate_fast_q15.c \
DSP/Source/FilteringFunctions/arm_correlate_fast_q31.c \
DSP/Source/FilteringFunctions/arm_correlate_opt_q15.c \
DSP/Source/FilteringFunctions/arm_correlate_opt_q7.c \
DSP/Source/FilteringFunctions/arm_correlate_q15.c \
DSP/Source/FilteringFunctions/arm_correlate_q31.c \
DSP/Source/FilteringFunctions/arm_correlate_q7.c \
DSP/Source/FilteringFunctions/arm_fir_decimate_f32.c \
DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q15.c \
DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q31.c \
DSP/Source/FilteringFunctions/arm_fir_decimate_init_f32.c \
DSP/Source/FilteringFunctions/arm_fir_decimate_init_q15.c \
DSP/Source/FilteringFunctions/arm_fir_decimate_init_q31.c \
DSP/Source/FilteringFunctions/arm_fir_decimate_q15.c \
DSP/Source/FilteringFunctions/arm_fir_decimate_q31.c \
DSP/Source/FilteringFunctions/arm_fir_f32.c \
DSP/Source/FilteringFunctions/arm_fir_fast_q15.c \
DSP/Source/FilteringFunctions/arm_fir_fast_q31.c \
DSP/Source/FilteringFunctions/arm_fir_init_f32.c \
DSP/Source/FilteringFunctions/arm_fir_init_q15.c \
DSP/Source/FilteringFunctions/arm_fir_init_q31.c \
DSP/Source/FilteringFunctions/arm_fir_init_q7.c \
DSP/Source/FilteringFunctions/arm_fir_interpolate_f32.c \
DSP/Source/FilteringFunctions/arm_fir_interpolate_init_f32.c \
DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q15.c \
DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q31.c \
DSP/Source/FilteringFunctions/arm_fir_interpolate_q15.c \
DSP/Source/FilteringFunctions/arm_fir_interpolate_q31.c \
DSP/Source/FilteringFunctions/arm_fir_lattice_f32.c \
DSP/Source/FilteringFunctions/arm_fir_lattice_init_f32.c \
DSP/Source/FilteringFunctions/arm_fir_lattice_init_q15.c \
DSP/Source/FilteringFunctions/arm_fir_lattice_init_q31.c \
DSP/Source/FilteringFunctions/arm_fir_lattice_q15.c \
DSP/Source/FilteringFunctions/arm_fir_lattice_q31.c \
DSP/Source/FilteringFunctions/arm_fir_q15.c \
DSP/Source/FilteringFunctions/arm_fir_q31.c \
DSP/Source/FilteringFunctions/arm_fir_q7.c \
DSP/Source/FilteringFunctions/arm_fir_sparse_f32.c \
DSP/Source/FilteringFunctions/arm_fir_sparse_init_f32.c \
DSP/Source/FilteringFunctions/arm_fir_sparse_init_q15.c \
DSP/Source/FilteringFunctions/arm_fir_sparse_init_q31.c \
DSP/Source/FilteringFunctions/arm_fir_sparse_init_q7.c \
DSP/Source/FilteringFunctions/arm_fir_sparse_q15.c \
DSP/Source/FilteringFunctions/arm_fir_sparse_q31.c \
DSP/Source/FilteringFunctions/arm_fir_sparse_q7.c \
DSP/Source/FilteringFunctions/arm_iir_lattice_f32.c \
DSP/Source/FilteringFunctions/arm_iir_lattice_init_f32.c \
DSP/Source/FilteringFunctions/arm_iir_lattice_init_q15.c \
DSP/Source/FilteringFunctions/arm_iir_lattice_init_q31.c \
DSP/Source/FilteringFunctions/arm_iir_lattice_q15.c \
DSP/Source/FilteringFunctions/arm_iir_lattice_q31.c \
DSP/Source/FilteringFunctions/arm_lms_f32.c \
DSP/Source/FilteringFunctions/arm_lms_init_f32.c \
DSP/Source/FilteringFunctions/arm_lms_init_q15.c \
DSP/Source/FilteringFunctions/arm_lms_init_q31.c \
DSP/Source/FilteringFunctions/arm_lms_norm_f32.c \
DSP/Source/FilteringFunctions/arm_lms_norm_init_f32.c \
DSP/Source/FilteringFunctions/arm_lms_norm_init_q15.c \
DSP/Source/FilteringFunctions/arm_lms_norm_init_q31.c \
DSP/Source/FilteringFunctions/arm_lms_norm_q15.c \
DSP/Source/FilteringFunctions/arm_lms_norm_q31.c \
DSP/Source/FilteringFunctions/arm_lms_q15.c \
DSP/Source/FilteringFunctions/arm_lms_q31.c \
DSP/Source/MatrixFunctions/arm_mat_add_f32.c \
DSP/Source/MatrixFunctions/arm_mat_add_q15.c \
DSP/Source/MatrixFunctions/arm_mat_add_q31.c \
DSP/Source/MatrixFunctions/arm_mat_cmplx_mult_f32.c \
DSP/Source/MatrixFunctions/arm_mat_cmplx_mult_q15.c \
DSP/Source/MatrixFunctions/arm_mat_cmplx_mult_q31.c \
DSP/Source/MatrixFunctions/arm_mat_init_f32.c \
DSP/Source/MatrixFunctions/arm_mat_init_q15.c \
DSP/Source/MatrixFunctions/arm_mat_init_q31.c \
DSP/Source/MatrixFunctions/arm_mat_inverse_f32.c \
DSP/Source/MatrixFunctions/arm_mat_inverse_f64.c \
DSP/Source/MatrixFunctions/arm_mat_mult_f32.c \
DSP/Source/MatrixFunctions/arm_mat_mult_fast_q15.c \
DSP/Source/MatrixFunctions/arm_mat_mult_fast_q31.c \
DSP/Source/MatrixFunctions/arm_mat_mult_q15.c \
DSP/Source/MatrixFunctions/arm_mat_mult_q31.c \
DSP/Source/MatrixFunctions/arm_mat_scale_f32.c \
DSP/Source/MatrixFunctions/arm_mat_scale_q15.c \
DSP/Source/MatrixFunctions/arm_mat_scale_q31.c \
DSP/Source/MatrixFunctions/arm_mat_sub_f32.c \
DSP/Source/MatrixFunctions/arm_mat_sub_q15.c \
DSP/Source/MatrixFunctions/arm_mat_sub_q31.c \
DSP/Source/MatrixFunctions/arm_mat_trans_f32.c \
DSP/Source/MatrixFunctions/arm_mat_trans_q15.c \
DSP/Source/MatrixFunctions/arm_mat_trans_q31.c \
DSP/Source/StatisticsFunctions/arm_max_f32.c \
DSP/Source/StatisticsFunctions/arm_max_q15.c \
DSP/Source/StatisticsFunctions/arm_max_q31.c \
DSP/Source/StatisticsFunctions/arm_max_q7.c \
DSP/Source/StatisticsFunctions/arm_mean_f32.c \
DSP/Source/StatisticsFunctions/arm_mean_q15.c \
DSP/Source/StatisticsFunctions/arm_mean_q31.c \
DSP/Source/StatisticsFunctions/arm_mean_q7.c \
DSP/Source/StatisticsFunctions/arm_min_f32.c \
DSP/Source/StatisticsFunctions/arm_min_q15.c \
DSP/Source/StatisticsFunctions/arm_min_q31.c \
DSP/Source/StatisticsFunctions/arm_min_q7.c \
DSP/Source/StatisticsFunctions/arm_power_f32.c \
DSP/Source/StatisticsFunctions/arm_power_q15.c \
DSP/Source/StatisticsFunctions/arm_power_q31.c \
DSP/Source/StatisticsFunctions/arm_power_q7.c \
DSP/Source/StatisticsFunctions/arm_rms_f32.c \
DSP/Source/StatisticsFunctions/arm_rms_q15.c \
DSP/Source/StatisticsFunctions/arm_rms_q31.c \
DSP/Source/StatisticsFunctions/arm_std_f32.c \
DSP/Source/StatisticsFunctions/arm_std_q15.c \
DSP/Source/StatisticsFunctions/arm_std_q31.c \
DSP/Source/StatisticsFunctions/arm_var_f32.c \
DSP/Source/StatisticsFunctions/arm_var_q15.c \
DSP/Source/StatisticsFunctions/arm_var_q31.c \
DSP/Source/SupportFunctions/arm_copy_f32.c \
DSP/Source/SupportFunctions/arm_copy_q15.c \
DSP/Source/SupportFunctions/arm_copy_q31.c \
DSP/Source/SupportFunctions/arm_copy_q7.c \
DSP/Source/SupportFunctions/arm_fill_f32.c \
DSP/Source/SupportFunctions/arm_fill_q15.c \
DSP/Source/SupportFunctions/arm_fill_q31.c \
DSP/Source/SupportFunctions/arm_fill_q7.c \
DSP/Source/SupportFunctions/arm_float_to_q15.c \
DSP/Source/SupportFunctions/arm_float_to_q31.c \
DSP/Source/SupportFunctions/arm_float_to_q7.c \
DSP/Source/SupportFunctions/arm_q15_to_float.c \
DSP/Source/SupportFunctions/arm_q15_to_q31.c \
DSP/Source/SupportFunctions/arm_q15_to_q7.c \
DSP/Source/SupportFunctions/arm_q31_to_float.c \
DSP/Source/SupportFunctions/arm_q31_to_q15.c \
DSP/Source/SupportFunctions/arm_q31_to_q7.c \
DSP/Source/SupportFunctions/arm_q7_to_float.c \
DSP/Source/SupportFunctions/arm_q7_to_q15.c \
DSP/Source/SupportFunctions/arm_q7_to_q31.c \
DSP/Source/TransformFunctions/arm_bitreversal.c \
DSP/Source/TransformFunctions/arm_cfft_f32.c \
DSP/Source/TransformFunctions/arm_cfft_q15.c \
DSP/Source/TransformFunctions/arm_cfft_q31.c \
DSP/Source/TransformFunctions/arm_cfft_radix2_f32.c \
DSP/Source/TransformFunctions/arm_cfft_radix2_init_f32.c \
DSP/Source/TransformFunctions/arm_cfft_radix2_init_q15.c \
DSP/Source/TransformFunctions/arm_cfft_radix2_init_q31.c \
DSP/Source/TransformFunctions/arm_cfft_radix2_q15.c \
DSP/Source/TransformFunctions/arm_cfft_radix2_q31.c \
DSP/Source/TransformFunctions/arm_cfft_radix4_f32.c \
DSP/Source/TransformFunctions/arm_cfft_radix4_init_f32.c \
DSP/Source/TransformFunctions/arm_cfft_radix4_init_q15.c \
DSP/Source/TransformFunctions/arm_cfft_radix4_init_q31.c \
DSP/Source/TransformFunctions/arm_cfft_radix4_q15.c \
DSP/Source/TransformFunctions/arm_cfft_radix4_q31.c \
DSP/Source/TransformFunctions/arm_cfft_radix8_f32.c \
DSP/Source/TransformFunctions/arm_dct4_f32.c \
DSP/Source/TransformFunctions/arm_dct4_init_f32.c \
DSP/Source/TransformFunctions/arm_dct4_init_q15.c \
DSP/Source/TransformFunctions/arm_dct4_init_q31.c \
DSP/Source/TransformFunctions/arm_dct4_q15.c \
DSP/Source/TransformFunctions/arm_dct4_q31.c \
DSP/Source/TransformFunctions/arm_rfft_f32.c \
DSP/Source/TransformFunctions/arm_rfft_fast_f32.c \
DSP/Source/TransformFunctions/arm_rfft_fast_init_f32.c \
DSP/Source/TransformFunctions/arm_rfft_init_f32.c \
DSP/Source/TransformFunctions/arm_rfft_init_q15.c \
DSP/Source/TransformFunctions/arm_rfft_init_q31.c \
DSP/Source/TransformFunctions/arm_rfft_q15.c \
DSP/Source/TransformFunctions/arm_rfft_q31.c \
OLED/Src/customoled.c \
OLED/Src/oled.c \
PR/Src/pr.c \
PROTECT/Src/protect.c \
SOGI/Src/sogi.c \
UC/Src/usercode.c 


# ASM sources
ASM_SOURCES =  \
startup_stm32f407xx.s

# ASM sources
ASMM_SOURCES = \
DSP/Source/TransformFunctions/arm_bitreversal2.S


#######################################
# binaries
#######################################
PREFIX = arm-none-eabi-
# The gcc compiler bin path can be either defined in make command via GCC_PATH variable (> make GCC_PATH=xxx)
# either it can be added to the PATH environment variable.
ifdef GCC_PATH
CC = $(GCC_PATH)/$(PREFIX)gcc
AS = $(GCC_PATH)/$(PREFIX)gcc -x assembler-with-cpp
CP = $(GCC_PATH)/$(PREFIX)objcopy
SZ = $(GCC_PATH)/$(PREFIX)size
else
CC = $(PREFIX)gcc
AS = $(PREFIX)gcc -x assembler-with-cpp
CP = $(PREFIX)objcopy
SZ = $(PREFIX)size
endif
HEX = $(CP) -O ihex
BIN = $(CP) -O binary -S
 
#######################################
# CFLAGS
#######################################
# cpu
CPU = -mcpu=cortex-m4

# fpu
FPU = -mfpu=fpv4-sp-d16

# float-abi
FLOAT-ABI = -mfloat-abi=hard

# mcu
MCU = $(CPU) -mthumb $(FPU) $(FLOAT-ABI)

# macros for gcc
# AS defines
AS_DEFS = 

# C defines
C_DEFS =  \
-DUSE_HAL_DRIVER \
-DSTM32F407xx \
-DARM_MATH_LOOPUNROLL \
-DARM_MATH_CM4 \
-DARM_MATH_MATRIX_CHECK \
-DARM_MATH_ROUNDING \
-D__FPU_PRESENT=1 \
-D__FPU_USED \
-D__TARGET_FPU_VFP

# AS includes
AS_INCLUDES =  \
-ICore/Inc

# C includes
C_INCLUDES =  \
-ICore/Inc \
-IDrivers/STM32F4xx_HAL_Driver/Inc \
-IDrivers/STM32F4xx_HAL_Driver/Inc/Legacy \
-IMiddlewares/Third_Party/FreeRTOS/Source/include \
-IMiddlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 \
-IMiddlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F \
-IDrivers/CMSIS/Device/ST/STM32F4xx/Include \
-IDrivers/CMSIS/Include \
-IBUTTON/Inc \
-ICONTROL/Inc \
-IDSP/Inc \
-IOLED/Inc \
-IPR/Inc \
-IPROTECT/Inc \
-ISOGI/Inc \
-IUC/Inc


# compile gcc flags
ASFLAGS = $(MCU) $(AS_DEFS) $(AS_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

CFLAGS += $(MCU) $(C_DEFS) $(C_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

ifeq ($(DEBUG), 1)
CFLAGS += -g -gdwarf-2
endif

#######################################
# LDFLAGS
#######################################
# link script
LDSCRIPT = STM32F407VETx_FLASH.ld

# libraries
LIBS = -lc -lm -lnosys
LIBDIR = 
LDFLAGS = $(MCU) -specs=nano.specs -T$(LDSCRIPT) $(LIBDIR) $(LIBS) -Wl,-Map=$(BUILD_DIR)/$(TARGET).map,--cref -Wl,--gc-sections

# default action: build all
all: $(BUILD_DIR)/$(TARGET).elf $(BUILD_DIR)/$(TARGET).hex $(BUILD_DIR)/$(TARGET).bin



#######################################
# build the application
#######################################
# list of objects
OBJECTS = $(addprefix $(BUILD_DIR)/,$(notdir $(C_SOURCES:.c=.o)))
vpath %.c $(sort $(dir $(C_SOURCES)))
# list of ASM program objects
OBJECTS += $(addprefix $(BUILD_DIR)/,$(notdir $(ASM_SOURCES:.s=.o)))
vpath %.s $(sort $(dir $(ASM_SOURCES)))
OBJECTS += $(addprefix $(BUILD_DIR)/,$(notdir $(ASMM_SOURCES:.S=.o)))
vpath %.S $(sort $(dir $(ASMM_SOURCES)))

$(BUILD_DIR)/%.o: %.c Makefile | $(BUILD_DIR) 
	$(CC) -c $(CFLAGS) -Wa,-a,-ad,-alms=$(BUILD_DIR)/$(notdir $(<:.c=.lst)) $< -o $@

$(BUILD_DIR)/%.o: %.s Makefile | $(BUILD_DIR)
	$(AS) -c $(CFLAGS) $< -o $@
$(BUILD_DIR)/%.o: %.S Makefile | $(BUILD_DIR)
	$(AS) -c $(CFLAGS) $< -o $@

$(BUILD_DIR)/$(TARGET).elf: $(OBJECTS) Makefile
	$(CC) $(OBJECTS) $(LDFLAGS) -o $@
	$(SZ) $@

$(BUILD_DIR)/%.hex: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(HEX) $< $@
	
$(BUILD_DIR)/%.bin: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(BIN) $< $@	
	
$(BUILD_DIR):
	mkdir $@		

#######################################
# clean up
#######################################
clean:
	-rm -fR $(BUILD_DIR)
  
#######################################
# dependencies
#######################################
-include $(wildcard $(BUILD_DIR)/*.d)

# *** EOF ***